name: Make on push

on:
  push:
    paths:
      - meta/*
      - json/*
      - SKK-JISYO.*
      - zipcode/SKK-JISYO.*

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install packages
      run: |
        sudo apt update
        sudo apt -y install autoconf docdiff emacs nkf libdb-dev libglib2.0-dev

    - name: clone skktools
      uses: actions/checkout@v4
      with:
        repository: skk-dev/skktools
        path: tools
    - name: make skktools
      run: |
        cd tools
        ./configure
        make
        pwd >> $GITHUB_PATH

    - name: install deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        path: dict

    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages

    - name: make -C zipcode
      run: |
        cd dict
        cd zipcode
        autoconf -f
        ./configure
        make batch test

    - name: make
      run: |
        cd dict
        make MD5=md5sum gzip

    - name: prepare git user
      run: |
        cd dict
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: auto-push after make
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd dict
        git diff -wI '^;' --stat | grep SKK-JISYO && \
        git add -u && \
        git commit -m "auto-push after auto-make\n\n`git diff --staged --stat`" && \
        git push

    - name: upload dicts
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp dict/*.gz dict/*.md5 gh-pages/
        cd gh-pages
        git add -u && \
        git commit -m "update" && \
        git push

    - name: make wrong_check
      run: |
        cd dict
        make wrong_check
        for i in *.w; do echo $i; cat $i; echo; done
